# syntax=docker/dockerfile:1

FROM node:20-alpine AS builder
WORKDIR /app

# Install dependencies
COPY package*.json ./
COPY tsconfig*.json nest-cli.json ./
COPY apps apps
COPY libs libs
RUN npm ci

# Build only user-service (includes shared libs/proto)
RUN npm run build:user-service && mkdir -p dist/libs/proto && cp libs/proto/src/audit.proto dist/libs/proto/audit.proto

FROM node:20-alpine AS runner
WORKDIR /app

# Install only production deps
COPY package*.json package-lock.json ./
RUN npm ci --omit=dev

# Copy built artifacts
COPY --from=builder /app/dist ./dist
# Copy env template if you want defaults baked in (actual env passed at runtime)
COPY apps/user-service/.env.example ./apps/user-service/.env.example

ENV NODE_ENV=production
EXPOSE 3000

CMD ["node", "dist/apps/user-service/apps/user-service/src/main.js"]
